### ISSUE TITLE
add pls primary functioonal 

### ISSUE THREAD

**Issue by endorphin82** [imorte/golang-telegram-victorine-bot#10]
if new user comin  chat, bot will squeeze his ass

**Comment by endorphin82** [comment]
// https://medium.com/golang-notes/%D0%BF%D0%B8%D1%88%D0%B5%D0%BC-%D0%B1%D0%BE%D1%82%D0%B0-%D0%B4%D0%BB%D1%8F-telegram-%D0%BD%D0%B0-go-71c9acd102d1
	select {
		case update := <-bot.Updates:
			// Пользователь, который написал боту
			UserName := update.Message.From.UserName
			UserID := update.Message.From.ID

			// ID чата/диалога.
			// Может быть идентификатором как чата с пользователем
			// (тогда он равен UserID) так и публичного чата/канала
			ChatID := update.Message.Chat.ID

			// Текст сообщения
			Text := update.Message.Text

			log.Printf("[%s] %d %d %s", UserName, UserID, ChatID, Text)
			var reply string
			if update.Message.NewChatParticipant.UserName != "" {
				// В чат вошел новый пользователь
				// Поприветствуем его
				reply = fmt.Sprintf(`@%s, поверь, в этом чате очко всегда сжато.`,
					update.Message.NewChatParticipant.UserName)
			}

			if reply != "" {
				// Созадаем сообщение
				msg := tgbotapi.NewMessage(ChatID, reply)
				// и отправляем его
				bot.SendMessage(msg)
			}

		}

**Comment by imorte** [comment]
присылай пул реквест
